import Link from 'next/link';
import {requireUser} from '@/lib/auth';
import {repository} from '@/lib/repository';
import {getKeywordProgress,formatTime} from '@/lib/progress';
import {currentProviderId} from '@/lib/ranking';
import {providerLabel} from '@/lib/ranking/provider';
import {StatusBadge,ProgressBar,RankText} from '@/components/ui';
import {BulkCheck,CheckButton} from '@/components/actions';
export default async function Dashboard(){const user=await requireUser(),data=await (await repository(user.id)).snapshot();const provider=currentProviderId();const rows=data.keywords.map(k=>{const place=data.places.find(p=>p.id===k.place_id)!;return {k,place,p:getKeywordProgress(data.checks.filter(c=>c.place_keyword_id===k.id),place.start_date,k.target_rank,k.target_days)};});const active=rows.filter(r=>r.k.is_active&&r.place.is_active);const warning=active.filter(r=>r.p.remainingDays>0&&r.p.remainingDays<=5).length,completed=active.filter(r=>r.p.remainingDays===0).length;
 return <><div className="heading"><div><h1>관리 대시보드</h1><p className="subtitle">업장별 검색 순위와 누적 노출일을 확인하세요.</p></div><div className="actions"><BulkCheck ids={active.map(r=>r.k.id)}/><Link className="btn primary" href="/places/new">＋ 업장 등록</Link></div></div><section className="stats" aria-label="활성 키워드 요약"><div className="stat"><p>전체 관리 키워드</p><strong>{active.length}<span className="muted"> 개</span></strong></div><div className="stat"><p>진행중</p><strong>{active.length-warning-completed}</strong></div><div className="stat warn"><p>D-5 이하 경고</p><strong>{warning}</strong></div><div className="stat done"><p>목표달성</p><strong>{completed}</strong></div></section><section className="panel"><div className="panel-head"><h2>키워드 관리 현황</h2><span className="muted">{providerLabel(provider)}</span></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>업장 / 검색키워드</th><th>오늘 대표순위</th><th>누적 노출일</th><th>남은 일수</th><th>상태</th><th>마지막 체크</th><th>관리</th></tr></thead><tbody>{rows.map(({k,place,p})=><tr key={k.id}><td><Link className="primary-text" href={`/places/${place.id}`}>{place.name}</Link><p className="muted">{k.keyword} · {k.target_rank}위 이내</p>{(!k.is_active||!place.is_active)&&<span className="badge">비활성</span>}</td><td><RankText rank={p.todayRank} checked={p.todayChecked}/></td><td><strong>{p.achievedDays} / {k.target_days}일</strong><span className="muted"> · {p.progress}%</span><ProgressBar value={p.progress}/></td><td>{p.remainingDays}일</td><td><StatusBadge remaining={p.remainingDays}/></td><td className="muted">{formatTime(p.lastChecked)}</td><td><CheckButton id={k.id} provider={provider} disabled={!k.is_active||!place.is_active}/><Link className="link" href={`/places/${place.id}#keyword-${k.id}`}>상세보기 →</Link></td></tr>)}</tbody></table></div>:<div className="empty"><h2>{data.places.length?'등록된 검색키워드가 없습니다.':'아직 등록된 업장이 없습니다.'}</h2><p>첫 업장과 검색키워드를 등록하고 목표 관리를 시작해보세요.</p><Link className="btn primary" href="/places/new">업장 등록</Link></div>}</section>{data.places.length>0&&<section className="panel"><div className="panel-head"><h2>등록 업장 <span className="muted">{data.places.length}곳</span></h2></div><div className="panel-body actions">{data.places.map(place=><Link key={place.id} className="btn" href={`/places/${place.id}`}>{place.name}{!place.is_active?' · 비활성':''}</Link>)}</div></section>}<p className="footnote">한 날짜에 목표 순위 이내 기록이 하나라도 있으면 1일로 인정합니다. 순위가 내려가도 누적일은 유지됩니다. 요약은 활성 업장·키워드 기준입니다.</p></>;
}
