import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireUser} from '@/lib/auth';
import {repository} from '@/lib/repository';
import {currentProviderId} from '@/lib/ranking';
import {providerLabel} from '@/lib/ranking/provider';
import {localDemo} from '@/lib/config';
import {getKeywordProgress,dailyRecords,formatTime} from '@/lib/progress';
import {StatusBadge,ProgressStats} from '@/components/ui';
import {CheckButton,DeleteButton,SeedHistory} from '@/components/actions';
import {KeywordForm} from '@/components/forms';
export default async function PlaceDetail({params}:{params:Promise<{id:string}>}){const {id}=await params,user=await requireUser(),data=await (await repository(user.id)).snapshot(),place=data.places.find(p=>p.id===id);if(!place)notFound();const keywords=data.keywords.filter(k=>k.place_id===id),provider=currentProviderId();return <><div className="heading"><div><Link className="link" href="/dashboard">← 대시보드</Link><h1>{place.name}</h1><p className="subtitle">{place.address}</p><div className="detail-meta"><span>검색용 업체명 · {place.search_name}</span><span>관리 시작 · {place.start_date}</span><span className="badge">{place.is_active?'활성':'비활성'}</span></div></div><div className="actions"><Link className="btn" href={`/places/${id}/edit`}>업장 수정</Link><DeleteButton id={id} place/></div></div><section className="panel"><div className="panel-head"><h2>검색키워드 <span className="muted">{keywords.length}개</span></h2><span className="muted">{providerLabel(provider)}</span></div>{keywords.length?keywords.map(k=>{const checks=data.checks.filter(c=>c.place_keyword_id===k.id),p=getKeywordProgress(checks,place.start_date,k.target_rank,k.target_days),daily=dailyRecords(checks,k.target_rank,place.start_date);return <article className="keyword-card" key={k.id} id={`keyword-${k.id}`}><div className="heading"><div><div className="status-row"><h2>{k.keyword}</h2><StatusBadge remaining={p.remainingDays}/>{!k.is_active&&<span className="badge">비활성</span>}</div><p className="muted">목표 {k.target_rank}위 이내 · 누적 {k.target_days}일</p></div><CheckButton id={k.id} provider={provider} disabled={!k.is_active||!place.is_active}/></div><ProgressStats p={p} target={k.target_days}/><details><summary>키워드 수정 / 활성 설정</summary><p className="muted mb-4">목표를 변경하면 기존 기록도 새 목표로 다시 계산됩니다.</p><KeywordForm placeId={id} keyword={k}/><div className="mt-4"><DeleteButton id={k.id}/></div></details>{localDemo()&&provider==='mock'&&<SeedHistory id={k.id}/>}<details open><summary>날짜별 기록 · {daily.length}일</summary>{daily.length?<div className="table-wrap"><table><thead><tr><th>날짜</th><th>대표순위</th><th>상위노출 인정</th><th>조회횟수</th><th>마지막 체크</th><th>조회 기준</th></tr></thead><tbody>{daily.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.rank===null?'조회범위 밖':`${d.rank}위`}</td><td><span className={`badge ${d.recognized?'complete':''}`}>{d.recognized?'인정':d.date<place.start_date?'시작일 이전':'미인정'}</span></td><td>{d.count}회</td><td>{formatTime(d.last)}</td><td>{d.providers.split(', ').map(providerLabel).join(', ')}</td></tr>)}</tbody></table></div>:<p className="muted">아직 조회기록이 없습니다. 지금 순위를 체크해보세요.</p>}</details></article>;}):<div className="empty"><p>아직 검색키워드가 없습니다. 아래에서 추가해주세요.</p></div>}</section><section className="panel"><div className="panel-head"><h2>검색키워드 추가</h2></div><div className="panel-body"><KeywordForm placeId={id}/></div></section><p className="footnote">Mock와 실제 API 기록은 조회 기준을 구분해 보관합니다. 테스트를 마친 후에는 테스트 업장을 삭제하고 실제 관리 업장을 새로 등록하세요.</p></>;}
