'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {send} from './actions';
import type {Place,Keyword} from '@/lib/types';
const text=(f:FormData,k:string)=>String(f.get(k)??'');
function keywordInput(f:FormData){return {keyword:text(f,'keyword'),target_rank:Number(f.get('target_rank')),target_days:Number(f.get('target_days')),is_active:f.get('keyword_active')==='on'};}
function KeywordFields({keyword}:{keyword?:Keyword}){return <><label className="field">검색키워드<input name="keyword" defaultValue={keyword?.keyword} placeholder="예: 목동 치과" required maxLength={100}/></label><div className="grid2"><label className="field">목표 순위 (이내)<input name="target_rank" type="number" min={1} max={1000} defaultValue={keyword?.target_rank??5} required/></label><label className="field">목표 누적일<input name="target_days" type="number" min={1} max={3650} defaultValue={keyword?.target_days??25} required/></label></div><label className="check-field"><input name="keyword_active" type="checkbox" defaultChecked={keyword?.is_active??true}/>검색키워드 활성</label></>;}
export function PlaceForm({place,today}:{place?:Place;today:string}){const router=useRouter(),[pending,setPending]=useState(false),[error,setError]=useState('');async function submit(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setPending(true);setError('');const input={name:text(f,'name'),search_name:text(f,'search_name'),address:text(f,'address'),start_date:text(f,'start_date'),is_active:f.get('is_active')==='on'};try{const result=await send(place?{action:'updatePlace',id:place.id,place:input}:{action:'createPlace',place:input,keyword:keywordInput(f)});router.push(`/places/${place?.id??result.id}`);router.refresh();}catch(e){setError((e as Error).message);setPending(false);}}return <form className="form" onSubmit={submit}><fieldset disabled={pending}><div className="grid2"><label className="field">관리용 업장명<input name="name" defaultValue={place?.name} placeholder="예: ABC치과" required maxLength={100}/></label><label className="field">검색용 실제 업체명<input name="search_name" defaultValue={place?.search_name} placeholder="예: ABC치과 목동점" required maxLength={150}/></label></div><label className="field">주소<input name="address" defaultValue={place?.address} placeholder="검색결과의 도로명주소 또는 지번주소 전체" required maxLength={300}/><small>지역검색 API는 업체명과 주소가 모두 일치할 때만 같은 업장으로 판단합니다.</small></label><label className="field">관리 시작일<input name="start_date" type="date" defaultValue={place?.start_date??today} required/></label><label className="check-field"><input name="is_active" type="checkbox" defaultChecked={place?.is_active??true}/>업장 순위 관리 활성</label>{!place&&<section className="form-divider"><h2 className="mb-5">첫 검색키워드</h2><KeywordFields/></section>}{error&&<p role="alert" className="feedback error">{error}</p>}<button className="btn primary">{pending?'저장 중...':place?'변경사항 저장':'업장 등록'}</button></fieldset></form>;}
export function KeywordForm({placeId,keyword}:{placeId:string;keyword?:Keyword}){const router=useRouter(),[pending,setPending]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);async function submit(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=keywordInput(new FormData(form));setPending(true);setMessage('');try{await send(keyword?{action:'updateKeyword',id:keyword.id,keyword:data}:{action:'addKeyword',placeId,keyword:data});setMessage('저장되었습니다.');setError(false);if(!keyword)form.reset();router.refresh();}catch(e){setMessage((e as Error).message);setError(true);}finally{setPending(false);}}return <form className="form" onSubmit={submit}><fieldset disabled={pending}><KeywordFields keyword={keyword}/><button className="btn primary small">{pending?'저장 중...':keyword?'키워드 저장':'키워드 추가'}</button>{message&&<p className={`feedback ${error?'error':''}`} role={error?'alert':'status'}>{message}</p>}</fieldset></form>;}
